baseURL = "http://journal.jinnzhong.com/"
languageCode = "en-us"
title = "Repository of Notes"
theme = "etch"
enableInlineShortcodes = true
enableEmoji = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "Jinn's Not-So-Secret Repository of Notes"
  copyright = "Copyright © 2001-2024 Jinn Zhong"
  dark = "on"
  highlight = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "ntes"
    title = "ntes"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "categories"
    name = "ctgs"
    title = "ctgs"
    url = "/categories/"
    weight = 20
    
[[menu.main]]
    identifier = "tags"
    name = "tags"
    title = "tags"
    url = "/tags/"
    weight = 30

[[menu.main]]
    identifier = "cipher"
    name = "cphr"
    title = "cphr"
    url = "/cipher/"
    weight = 40

[[menu.main]]
    identifier = "about"
    name = "abt"
    title = "abt"
    url = "/about/"
    weight = 50

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allow HTML in Markdown
  unsafe = true

  [markup.tableOfContents]
    ordered = true
