baseURL = "http://journal.jinnzhong.com/"
languageCode = "en-us"
title = "Repository of Notes"
theme = "etch"
paginate = 23
enableInlineShortcodes = true
enableEmoji = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "Jinn's Not-So-Secret Repository of Notes"
  copyright = "Copyright © 2001-2025 Jinn Zhong"
  dark = "on"
  highlight = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "ntes"
    title = "ntes"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "categories"
    name = "ctgs"
    title = "ctgs"
    url = "/categories/"
    weight = 20

[[menu.main]]
    identifier = "projects"
    name = "prjs"
    title = "prjs"
    url = "/projects/"
    weight = 30
    
[[menu.main]]
    identifier = "tracker"
    name = "trkr"
    title = "trkr"
    url = "/tracker/"
    weight = 40

[[menu.main]]
    identifier = "about"
    name = "abt"
    title = "abt"
    url = "/about/"
    weight = 50

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allow HTML in Markdown
  unsafe = true

[markup.tableOfContents]
    ordered = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[[redirects]]
	from = "/*"
	to = "/404/"
	status = 404
